extends RefCounted
class_name RoleProfiles

const ROLE_PROFILES: Dictionary = {
	"player_doctor_001": {
		"npc_id": "player_doctor_001",
		"display_name": "玩家医生",
		"role": "player",
		"floor": "F1",
		"home_location": "ED_ENTRANCE",
		"spawn_position": Vector2(400.0, 350.0),
		"patrol_area": [Vector2(360.0, 320.0), Vector2(460.0, 420.0)],
		"idle_mode": "controlled",
		"background": "Room1 baseline player doctor.",
		"llm_enabled": false,
		"resource_role": null,
		"scheduler_eligible": false,
		"current_goal": "player_control",
	},
	"triage_nurse_001": {
		"npc_id": "triage_nurse_001",
		"display_name": "分诊护士 1",
		"role": "nurse",
		"floor": "F1",
		"home_location": "TRIAGE",
		"spawn_position": Vector2(550.0, 300.0),
		"patrol_area": [Vector2(500.0, 260.0), Vector2(620.0, 360.0)],
		"idle_mode": "wait_patient",
		"background": "Triage desk intake nurse.",
		"llm_enabled": false,
		"resource_role": "triage",
		"scheduler_eligible": true,
		"current_goal": "triage_intake",
	},
	"triage_nurse_002": {
		"npc_id": "triage_nurse_002",
		"display_name": "分诊护士 2",
		"role": "nurse",
		"floor": "F1",
		"home_location": "TRIAGE",
		"spawn_position": Vector2(650.0, 280.0),
		"patrol_area": [Vector2(620.0, 250.0), Vector2(740.0, 350.0)],
		"idle_mode": "assist_triage",
		"background": "Backup triage nurse.",
		"llm_enabled": false,
		"resource_role": "triage",
		"scheduler_eligible": true,
		"current_goal": "triage_support",
	},
	"emergency_nurse_001": {
		"npc_id": "emergency_nurse_001",
		"display_name": "急救护士 1",
		"role": "nurse",
		"floor": "F1",
		"home_location": "ED_RESUS",
		"spawn_position": Vector2(350.0, 450.0),
		"patrol_area": [Vector2(300.0, 410.0), Vector2(470.0, 520.0)],
		"idle_mode": "watch_resus",
		"background": "Emergency resus nurse.",
		"llm_enabled": false,
		"resource_role": "resus",
		"scheduler_eligible": true,
		"current_goal": "stabilize_critical_case",
	},
	"doctor_green_001": {
		"npc_id": "doctor_green_001",
		"display_name": "绿色医生 1",
		"role": "doctor",
		"floor": "F1",
		"home_location": "DOCTOR",
		"spawn_position": Vector2(650.0, 400.0),
		"patrol_area": [Vector2(610.0, 360.0), Vector2(760.0, 470.0)],
		"idle_mode": "consult",
		"background": "General ED doctor for first contact.",
		"llm_enabled": true,
		"resource_role": "doctor",
		"scheduler_eligible": true,
		"current_goal": "first_contact_consult",
	},
	"doctor_red_001": {
		"npc_id": "doctor_red_001",
		"display_name": "红色医生 1",
		"role": "doctor",
		"floor": "F1",
		"home_location": "DOCTOR",
		"spawn_position": Vector2(760.0, 350.0),
		"patrol_area": [Vector2(720.0, 320.0), Vector2(880.0, 450.0)],
		"idle_mode": "consult",
		"background": "Backup consulting doctor.",
		"llm_enabled": true,
		"resource_role": "doctor",
		"scheduler_eligible": true,
		"current_goal": "consult_and_order_tests",
	},
	"patient_spawn_point": {
		"npc_id": "patient_spawn_point",
		"display_name": "病人出生点",
		"role": "spawn_point",
		"floor": "F1",
		"home_location": "ED_ENTRANCE",
		"spawn_position": Vector2(450.0, 450.0),
		"patrol_area": [Vector2(430.0, 430.0), Vector2(500.0, 500.0)],
		"idle_mode": "spawn_only",
		"background": "Synthetic patient spawn marker for demos.",
		"llm_enabled": false,
		"resource_role": "spawn_point",
		"scheduler_eligible": false,
		"current_goal": "spawn_patient",
	},
	"lab_nurse_001": {
		"npc_id": "lab_nurse_001",
		"display_name": "检验护士 1",
		"role": "nurse",
		"floor": "F2",
		"home_location": "LAB",
		"spawn_position": Vector2(220.0, 240.0),
		"patrol_area": [Vector2(160.0, 210.0), Vector2(320.0, 320.0)],
		"idle_mode": "lab_support",
		"background": "Lab support nurse.",
		"llm_enabled": true,
		"resource_role": "lab",
		"scheduler_eligible": true,
		"current_goal": "lab_processing",
	},
	"lab_technician_001": {
		"npc_id": "lab_technician_001",
		"display_name": "检验技师 1",
		"role": "technician",
		"floor": "F2",
		"home_location": "LAB",
		"spawn_position": Vector2(300.0, 260.0),
		"patrol_area": [Vector2(260.0, 220.0), Vector2(380.0, 320.0)],
		"idle_mode": "lab_tech",
		"background": "Lab technician who processes samples.",
		"llm_enabled": true,
		"resource_role": "lab",
		"scheduler_eligible": true,
		"current_goal": "process_samples",
	},
	"surgeon_001": {
		"npc_id": "surgeon_001",
		"display_name": "外科医生 1",
		"role": "surgeon",
		"floor": "F2",
		"home_location": "RESULT_REVIEW",
		"spawn_position": Vector2(700.0, 240.0),
		"patrol_area": [Vector2(640.0, 200.0), Vector2(820.0, 330.0)],
		"idle_mode": "review_case",
		"background": "Surgical review doctor.",
		"llm_enabled": true,
		"resource_role": "surgery",
		"scheduler_eligible": true,
		"current_goal": "review_result_and_consult",
	},
	"ward_nurse_001": {
		"npc_id": "ward_nurse_001",
		"display_name": "住院护士 1",
		"role": "nurse",
		"floor": "F3",
		"home_location": "WARD",
		"spawn_position": Vector2(540.0, 260.0),
		"patrol_area": [Vector2(500.0, 220.0), Vector2(650.0, 340.0)],
		"idle_mode": "ward_support",
		"background": "Ward nurse handling admissions.",
		"llm_enabled": true,
		"resource_role": "ward",
		"scheduler_eligible": true,
		"current_goal": "ward_admission_support",
	},
	"qa_officer_001": {
		"npc_id": "qa_officer_001",
		"display_name": "质控官 1",
		"role": "qa",
		"floor": "F3",
		"home_location": "DISPOSITION",
		"spawn_position": Vector2(220.0, 260.0),
		"patrol_area": [Vector2(180.0, 220.0), Vector2(320.0, 340.0)],
		"idle_mode": "audit",
		"background": "Quality assurance observer.",
		"llm_enabled": true,
		"resource_role": "qa",
		"scheduler_eligible": true,
		"current_goal": "audit_flow_and_outcome",
	},
}

static func get_profile(npc_id: String) -> Dictionary:
	var profile_value: Variant = ROLE_PROFILES.get(npc_id, {})
	if typeof(profile_value) == TYPE_DICTIONARY:
		return profile_value as Dictionary
	return {}

static func get_profiles_for_floor(floor_id: String) -> Array:
	var profiles: Array = []
	for npc_id_value: Variant in ROLE_PROFILES.keys():
		var npc_id: String = str(npc_id_value)
		var profile: Dictionary = get_profile(npc_id)
		if str(profile.get("floor", "")) == floor_id:
			profiles.append(profile)
	return profiles

